language: go
sudo: false
go:
  - 1.6.x
  - 1.7.x
  - 1.8.x
  - 1.9.x
  - master
git:
  depth: 3

go_import_path:
  - github.com/plopezm/config
  - github.com/plopezm/manager
  - github.com/plopezm/metadata
