language: go
sudo: false
go:
  - 1.9.x
  - master
git:
  depth: 3

before_install:
  - go get -t -v ./...

script:
  - cd tests
  - go test -race -coverprofile=coverage.txt -covermode=atomic
  - mv coverage.txt ../
  - cd ..

after_success:
  - bash <(curl -s https://codecov.io/bash)