language: go
sudo: false
go:
  - 1.9.x
  - master
git:
  depth: 3

before_install:
  - go get -t -v ./...

script:
  - chmod +x launch_tests.sh
  - ./launch_tests.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)